service: bothrwebhook 
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "ssm:GetParameters"
     Resource: "arn:aws:ssm:ap-southeast-1:330344440711:parameter/*"
functions:
  bothrWebhook:
    handler: handler.bothrWebhook
    events:
    - http:
        path: bothrwebhook
        method: post
plugins:
  - serverless-offline